# Need Ubuntu trusty to install pip3
dist: trusty

sudo: required

jdk: oraclejdk8
python: 3.5
language: scala
services: docker

install:
  - sudo apt-get -qqy update
  - sudo apt-get -qqy install python3-setuptools
  - sudo easy_install3 -U pip
  - pip3 install --user git+git://github.com/typesafehub/conductr-cli.git@master
  # Ensure that our sandbox interfaces are prepared
  - sudo /sbin/ifconfig lo:0 192.168.10.1 netmask 255.255.255.255 up
  - sudo /sbin/ifconfig lo:1 192.168.10.2 netmask 255.255.255.255 up
  - sudo /sbin/ifconfig lo:2 192.168.10.3 netmask 255.255.255.255 up
  # Prep our sandbox with some temporary credentials for CI
  - ./bin/create-credentials.sh
  # Warm up some caches so that our tests don't timeout
  - sandbox run 2.0.5 -f visualization -f monitoring > /dev/null
  - conduct load -q cassandra
  - conduct load -q cinnamon-grafana-docker
  - conduct load -q eslite
  - conduct load -q reactive-maps-backend-region
  - conduct load -q reactive-maps-backend-summary
  - sandbox stop
  # Tests go faster if we do this... less interactions with bintray etc.
  - export CONDUCTR_OFFLINE_MODE=1

script: sbt "scripted public/*"
